paths:
  dumpcap: "C:/Program Files/Wireshark/dumpcap.exe"   # Wireshark instalowany z instalatora
  java: "java"                                        # Java instalowana z instalatora (na PATH)
  cicflowmeter_jar: "./tools/cicflowmeter/CICFlowMeterV3-0.0.4-SNAPSHOT.jar"
  jnetpcap_jar: "./tools/jnetpcap/jnetpcap.jar"
  jnetpcap_dll_dir: "./tools/jnetpcap"

capture:
  pcap_dir: "./runtime/pcaps"
  flows_dir: "./runtime/flows"

model:
  preproc_path: "./artifacts/preproc.joblib"
  rf_path: "./artifacts/rf.joblib"
  lstm_path: "./artifacts/lstm.keras.best.keras"
  seq_len: 20
  alert_threshold: 0.50


ui:
  max_alert_rows: 500
